#> according with Neil's request:
#> Could you generate an alternative version of the Colombia dept epi data:
#> where the iso week csv is generated by normalising each year's cases in a dept (say to sum to 1), 
#> then averaging those normalised seasonal profiles across years, 
#> and then finally multiplying the average normalised profile by the total number of cases across all years? 
#> The resulting file should be in the same format as the current one, 
#> and like the current one, the total number of cases in each column should be the total number of cases across
#>  included years for that department.
#>  It's just the relative weight of each year to the profile which is being tweaked.
#> The reason for doing so is to isolate year-to-year variation in numbers of cases from overall seasonal variation in transmission. At the moment, the seasonal profile can be skewed by years with very large numbers of cases.

rm(list=ls())

library(dplyr)
library(lubridate)
library(tidyr)
library(purrr)

selected_dpt = c("antioquia", 
                 "atlantico", 
                 "bolivar", 
                 "boyaca",
                 "caldas",
                 "cauca",  
                 "cesar",
                 "cordoba", 
                 "cundinamarca", 
                 "guajira",
                 "huila", 
                 "magdalena", 
                 "meta",
                 "narino", 
                 "norte_santander",
                 "risaralda",
                 "santander", 
                 "sucre",
                 "valle",  
                 "tolima")

# importo il database
#> importo comunque un database con i casi filtrati <23000 mt e con tante classi di età
df <- readRDS("COL/Dengue/Data/wrangled for Odin/dfDengue_21_less2300_DPT_full.RDS")# readRDS("COL/Dengue/Data/COL_Dengue_Zulma2008_EF_moreAges_low2300.RDS")
df_long = pivot_longer(df, 4:23,
                       names_to = "department",
                       values_to = "cases")

# Filtra i dipartimenti e calcola il totale per anno
df_weight <- df_long %>%
  filter(department %in% selected_dpt) %>%
  group_by(department, isoyear) %>%
  mutate(
    cases_tot = sum(cases, na.rm = TRUE),
    caseW = if_else(cases_tot > 0, cases / cases_tot, 0)
  ) %>%
  ungroup()

# check 
df_weight %>%
  group_by(department, isoyear) %>%
  summarise(check = sum(caseW))

# Profilo stagionale medio
df_seasonal <- df_weight %>%
  group_by(department, isoweek) %>%
  summarise(
    seasonal_profile = mean(caseW, na.rm = TRUE),
    .groups = "drop"
  )

# (Opzionale ma consigliato) rinormalizzazione
df_seasonal <- df_seasonal %>%
  group_by(department) %>%
  mutate(
    seasonal_profile = seasonal_profile / sum(seasonal_profile)
  ) %>%
  ungroup()
#> questo step mi serve per garantire che il profilo stagionale sia una vera distribuzione (nel caso ad esempio che ci siano settimane mancanti quindi NA che vengono ignorate dal sum)
#> Può non essere 1 Perchè: 
#>  settimane ISO mancanti in alcuni anni
#>  anni incompleti (inizio/fine serie)
#>  NA rimossi con na.rm = TRUE
#>  settimane 53 presenti solo in alcuni anni
#>  Quando è indispensabile
#>  se poi lo usi come peso
#>  se lo interpreti come distribuzione
#>  se lo moltiplichi per un totale (punto 4)

# Riscalare al totale dei casi osservati
df_tot <- df_long %>%
  filter(department %in% selected_dpt) %>%
  group_by(department) %>%
  summarise(
    total_cases = sum(cases, na.rm = TRUE),
    .groups = "drop"
  )

df_seasonal_scaled <- df_seasonal %>%
  left_join(df_tot, by = "department") %>%
  mutate(cases = seasonal_profile * total_cases)

#> questo serve a 
#> Serve a tornare alla scala dei casi osservati, mantenendo:
#> la forma stagionale “pulita”
#> il totale reale dei casi
#> 
#> Con il punto 4 ho:
#> una serie settimanale interpretabile come casi
#> stesso totale dell’osservato
#> ma senza dominanza degli anni epidemici
#> 

df_seasonal_scaled = df_seasonal_scaled %>%
  pivot_wider(
    names_from  = department,
    values_from = cases,
    values_fill = 0
  )

write.csv(
  df_seasonal_scaled,
  file = "COL/Dengue/Data/wrangled for Odin/dfDengue_21_less2300_DPT_week_SeasonalProfile.csv",
  row.names = FALSE
)

############## qui in poi NO

compute_seasonal_profile <- function(df_dep) {
  
  # totale casi su tutti gli anni
  total_cases <- sum(df_dep$casos, na.rm = TRUE)
  
  # normalizzazione per anno
  df_norm <- df_dep %>%
    group_by(year) %>%
    mutate(
      year_total = sum(casos, na.rm = TRUE),
      casos_norm = if_else(year_total > 0, casos / year_total, 0)
    ) %>%
    ungroup()
  
  # profilo stagionale medio
  seasonal_profile <- df_norm %>%
    group_by(iso_week) %>%
    summarise(
      mean_profile = mean(casos_norm, na.rm = TRUE),
      .groups = "drop"
    )
  
  # rinormalizzazione (sicurezza numerica)
  seasonal_profile <- seasonal_profile %>%
    mutate(mean_profile = mean_profile / sum(mean_profile))
  
  # riscalare al totale dei casi
  seasonal_profile <- seasonal_profile %>%
    mutate(casos = mean_profile * total_cases)
  
  return(seasonal_profile %>% select(iso_week, casos))
}

seasonal_corrected <- df_weekly %>%
  group_by(departamento) %>%
  group_split() %>%
  map_df(~ {
    compute_seasonal_profile(.x) %>%
      mutate(departamento = unique(.x$departamento))
  })

final_csv <- seasonal_corrected %>%
  pivot_wider(
    names_from = departamento,
    values_from = casos
  ) %>%
  arrange(iso_week)

# totale casi originali
original_totals <- df %>%
  group_by(departamento) %>%
  summarise(original = sum(casos, na.rm = TRUE))

# totale casi dopo la trasformazione
new_totals <- seasonal_corrected %>%
  group_by(departamento) %>%
  summarise(new = sum(casos, na.rm = TRUE))

check <- left_join(original_totals, new_totals, by = "departamento")

print(check)
